[2024-04-18 21:57:46,793] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:46] "[36mGET /openapi/static/images/apidoc.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:48,974] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:48] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:49,004] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:49] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:49,004] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:49] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:49,005] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:49] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:49,223] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:49] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:49,253] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:49] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:54,822] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:54] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:54,826] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:54] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:57,193] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:57] "[32mGET / HTTP/1.1[0m" 302 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:57:57,198] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:57:57] "GET /openapi/ HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:58:44,381] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:58:44] "POST /reserva HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:58:47,992] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-05-20', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 21:58:47,992] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:58:47] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:59:11,941] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:59:11] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 21:59:35,387] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 21:59:35] "DELETE /reserva?dataReserva_str=2024-04-30 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:00:00,864] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:00:00] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:00:50,971] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:00:50] "POST /reserva HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:05:45,414] WARNING add_reserva() L58   Erro ao adicionar a reserva '2024-04-30', Reserva de mesma data já salva na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L58  
[2024-04-18 22:05:45,415] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:05:45] "[31m[1mPOST /reserva HTTP/1.1[0m" 409 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:05:55,139] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:05:55] "OPTIONS /reserva?nome=7777777777 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:05:55,153] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:05:55] "DELETE /reserva?nome=7777777777 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:06:25,967] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:06:25] "POST /reserva HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:06:33,633] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:06:33] "OPTIONS /reserva?nome=8888888888888 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:06:33,646] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:06:33] "DELETE /reserva?nome=8888888888888 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:21,657] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:21] "OPTIONS /reserva?nome=466465465446654 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:21,661] WARNING del_reserva() L139  Erro ao deletar produto #'2024-04-30', Reserva não encontrada na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L139 
[2024-04-18 22:07:21,661] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:21] "[33mDELETE /reserva?nome=466465465446654 HTTP/1.1[0m" 404 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:27,808] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:27] "OPTIONS /reserva?nome=6666666666666 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:27,812] WARNING del_reserva() L139  Erro ao deletar produto #'2024-04-30', Reserva não encontrada na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L139 
[2024-04-18 22:07:27,813] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:27] "[33mDELETE /reserva?nome=6666666666666 HTTP/1.1[0m" 404 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:32,375] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:32] "OPTIONS /reserva?nome=11111111111111111 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:32,379] WARNING del_reserva() L139  Erro ao deletar produto #'2024-04-30', Reserva não encontrada na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L139 
[2024-04-18 22:07:32,381] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:32] "[33mDELETE /reserva?nome=11111111111111111 HTTP/1.1[0m" 404 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:40,203] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:40] "OPTIONS /reserva?nome=6666666666666 HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:40,207] WARNING del_reserva() L139  Erro ao deletar produto #'2024-04-30', Reserva não encontrada na base :/ - call_trace=C:\Users\anton\Documents\GitHub\Engenharia de Software PUC\1 modulo projeto\meu_app_api\app.py L139 
[2024-04-18 22:07:40,208] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:40] "[33mDELETE /reserva?nome=6666666666666 HTTP/1.1[0m" 404 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:07:51,246] INFO _log() L96   127.0.0.1 - - [18/Apr/2024 22:07:51] "GET /reservas HTTP/1.1" 200 - - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:17:08,206] INFO _log() L96   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.116:5000 - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
[2024-04-18 22:17:08,207] INFO _log() L96   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\anton\AppData\Local\Programs\Python\Python312\Lib\site-packages\werkzeug\_internal.py L96  
